server.port: 8080
server.static.classpath.location: /WEB
server.static.classpath.welcome: index.html

mp.messaging:
  connector:
    helidon-jms:
      jndi:
        # Connection factory jndi
        jms-factory: ConnectionFactory
        # Initial context properties
        env-properties:
          java.naming:
            factory.initial: org.apache.activemq.jndi.ActiveMQInitialContextFactory
            provider.url: tcp://localhost:61616

  incoming.from-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue

  outgoing.to-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue