server.port: 7001
server.static.classpath.location: /WEB
server.static.classpath.welcome: index.html

mp.messaging:
  connector:
    helidon-jms:
      named-factory: rabbit-mq-factory

  incoming.from-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue

  outgoing.to-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue